### ISSUE TITLE
4096バイト以上の文字列をtransformできない時がある

### ISSUE THREAD

**Issue by shigetaichi** [tomtwinkle/garbledreplacer#7]
こちら https://tech.andpad.co.jp/entry/2022/05/12/100000 の記事を読ませていただきました。
とても助かりました。ありがとうございます。

こちらのライブラリを使っていて、以下問題？に遭遇したので共有させていただきます🙇

```go
func main() {
	const msg = "一二三四🍣五六七八九🍺十拾壱"
	longMsg := strings.Repeat(msg, 4000) // 4096バイトを超えるようにする
	
	fp, err := os.Create("SJIS.txt")
	if err != nil {
		panic(err)
	}
	defer fp.Close()
	sjisWriter := bufio.NewWriter(transform.NewWriter(fp, garbledreplacer.NewTransformer(japanese.ShiftJIS, '?')))

	// 以下エラー処理省略
	_, err = sjisWriter.WriteString(longMsg)
	if err != nil {
		log.Fatal(err)
	}
	_ = sjisWriter.Flush()
}
```

上記のように、4096バイト以上の文字列をshift-jisに変換するとErrInvalidUTF8のエラーが出ます。
本来なら長い文字列でも問題なく変換できるのが良いと思います。

**Comment by shigetaichi** [comment]
自分で調査した中で見つけた解決策があるのでPRとしてあげております。

お時間ある時にぜひ見てみてください🙇

**Comment by tomtwinkle** [comment]
issueありがとうございます！
問題を確認します。

transformのdefaultBufSizeは4096バイトなので4096byteの境界で対象文字列があると問題が発生するかもしれません。
